### ISSUE TITLE
feat: Provide a hook that be called when first do custom mapping

### ISSUE THREAD

**Issue by mrbeardad** [brenton-leighton/multiple-cursors.nvim#10]
Some command require user input, says `surround`, get input in first call and feed the same input keys for subsequent call.
For example, 
```txt
          cursor1
           v
This is "st|ring"
This is "st|ring"
           ^
           cursor2
```
1. press `ds`, await user input
2. press `"`, delete the quote at cursor1
3. automatically `feedkeys("\"")` after call custom function at cursor2, thus, the subsequent calls no longer wait for user input

**Comment by mrbeardad** [comment]
The simplest solution maybe adding a parameter `is_init` for custom function.

![image](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/54128430/28a68a7b-cc6f-4444-979b-f4097dfca6ab)

**Comment by brenton-leighton** [comment]
Do you want to get a character after the command? I have implemented it with two functions in the `input` module:

- `get_motion_char()` for getting a valid motion character (so operator pending mode, like for normal mode `d` or `y`)
- `get_char()` for getting any printable character (like for normal mode `f` or `t`)

I think you can use the `get_char()` function like this:

```
local char = require("multiple-cursors.input").get_motion_char()
```

It returns nil if the character entered isn't valid

**Comment by brenton-leighton** [comment]
OK good point, let me see what I can do.

**Comment by mrbeardad** [comment]
I've made a pr #11 , is there anything duplicate with thie branch?

**Comment by mrbeardad** [comment]
Only get one char maybe not enough, for example, also surround, `cs<char1><char2>` to change surrounding `<char1>` to `<char2>`

**Comment by mrbeardad** [comment]
Yes, it works well.

**Comment by mrbeardad** [comment]
Maybe it could be more extensible.

```lua
custom_key_maps = {
  {"n", "<Leader>x", function(chars) vim.print(unpacked(chars)) end, {"c","m","o"}}
  -- "c" means any character, "m" means motion, "o" means textobj
}
```

**Comment by brenton-leighton** [comment]
> Maybe it could be more extensible.
> 
> ```lua
> custom_key_maps = {
>   {"n", "<Leader>x", function(chars) vim.print(unpacked(chars)) end, {"c","m","o"}}
>   -- "c" means any character, "m" means motion, "o" means textobj
> }
> ```

- I don't think it's possible to use one option to get an arbitrary number of characters, the wrapper function needs to know the number of characters to get from the user. I'm also not sure what the use case for more than two characters is.
- By _textobj_ do you mean treesitter text objects? I'm not sure how this will work, but I think they would be a per-cursor variable.
- I have had to make some changes to how elements in `custom_key_maps` are defined. Functions now receive `register` and `count1`, and then optionally `motion_cmd`, `char` or `char1, char2`. It's documented [here](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/get_two_chars?tab=readme-ov-file#custom_key_maps).

**Comment by brenton-leighton** [comment]
@mrbeardad by textobj do you mean [text object motions](https://neovim.io/doc/user/motion.html#object-motions) or [text object selection](https://neovim.io/doc/user/motion.html#object-select)?

In the [plugin_compatibility](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/plugin_compatibility) branch I've added support for text object selections for the `input.get_motion_cmd()` function. Is this what you wanted when you asked for getting two characters?

I've also added the custom key map option "mc" to get a motion command then a character. In theory this could be used for a surround command, but I've looked at [mini.surround](https://github.com/echasnovski/mini.surround) and [kylechui/nvim-surround](https://github.com/kylechui/nvim-surround) and they don't have functions that can be called with the motion and character as arguments.

The closest thing I can get working is to map a different command to the surround command, e.g. for mini.pairs:

```lua
custom_key_maps = {
  {"n", "<Leader>sa", function(_, count1, motion_cmd, char)
    vim.cmd("normal " .. count1 .. "sa" .. motion_cmd .. char)
  end, "mc"},
},
```

But since it uses a different command while multiple cursors is active it's not ideal.

**Comment by mrbeardad** [comment]
> In the [plugin_compatibility](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/plugin_compatibility) branch I've added support for text object selections for the input.get_motion_cmd() function. Is this what you wanted when you asked for getting two characters?

Yes, some motions require one char, such as `w`, and some require two char, such as `f{char}` and `aw`, even some require three char, such as `anw` in mini.surround. So it is hard to set all of these maps.

I've pre-researched using `q` macros recording to implement multiple cursors, the
demo is [here](https://github.com/mrbeardad/nvim-multi-cursor/blob/main/lua/nvim-multi-cursor/init.lua#L177), it seems successful. Thus, `custom_key_maps` is no longer needed. When user has done a completed normal command, repeat it at virtual cursors.
