### ISSUE TITLE
Add a command to move the cursor to the next word

### ISSUE THREAD

**Issue by aimuzov** [brenton-leighton/multiple-cursors.nvim#4]
Hello! Thank you for the plugin. I have a suggestion. Would it be possible for you to implement focus shifting similar to how it is done in vscode? For example, upon pressing <c-n>, it would highlight the next matching occurrence with the current selection (word).

### [Example](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor) from vscode docs:

![multicursor-word](https://github.com/brenton-leighton/multiple-cursors.nvim/assets/3313023/aebb74b3-bdbf-40b5-a2a0-2c2415148380)

**Comment by brenton-leighton** [comment]
I'm not sure, is this just creating cursors by searching for words? If so, that's already something I'm planning to do.

**Comment by brenton-leighton** [comment]
Hi @aimuzov, someone has submitted a [PR](https://github.com/brenton-leighton/multiple-cursors.nvim/pull/37) for a command like VS Code's Ctrl+D, so I realised that it adds a cursor one at a time. You could check [this branch](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/feat_add_cursor_to_next_match) to see if it works the way you want it to.

**Comment by brenton-leighton** [comment]
@bokenator mentioned [adding a command to skip a match](https://github.com/brenton-leighton/multiple-cursors.nvim/pull/37#issuecomment-1933313773).

I'm just wondering, what is the functionality that you want? If it's just incrementally adding cursors (rather than a copy of VS Code's Ctrl+D)?

I ask because maybe these two commands would work better:

1. Add virtual cursor to current cursor position, then jump to next match
2. Jump to next match (without adding a virtual cursor)

The first command would be the opposite of what Ctrl+D does (it doesn't move the real cursor, just adds a virtual cursor to the next match) but it would mean that the second command will give some feedback when a match is skipped.

@bokenator is that OK for you?

**Comment by bokenator** [comment]
I agree. The proposal is even better. It's definitely helpful to have some feedback when a shortcut key is pressed. The only shortcoming I can think of is it'll be harder to return to the original cursor's location, but it doesn't affect my workflow and it's easy to write a custom function that creates a mark at the original cursor.

**Comment by brenton-leighton** [comment]
I've added the functionality to the [feat_add_jump_next_match](https://github.com/brenton-leighton/multiple-cursors.nvim/tree/feat_add_jump_next_match) branch. There's two commands:

- `MultipleCursorsAddJumpNextMatch`: Add cursor and jump to next match
- `MultipleCursorsJumpNextMatch`: Jump to next match

The branch also renames the other search commands:

- `MultipleCursorsAddBySearch` has been renamed to `MultipleCursorsAddMatches`
- `MultipleCursorsAddBySearchV` has been renamed to `MultipleCursorsAddMatchesV`

@bokenator @aimuzov If there's no problems I will merge it.

@bokenator Restoring the cursor position when exiting multiple cursors sounds like a good idea, I'll probably add an option for that in the future.

**Comment by bokenator** [comment]
Sounds great!

Thanks you very much!

**Comment by brenton-leighton** [comment]
This is merged now. I'll tag a new release soon.
