### ISSUE TITLE
All is not working as expected

### ISSUE THREAD

**Issue by MrMic** [brenton-leighton/multiple-cursors.nvim#75]
Hi,

I work with AstroNvim and use neovim version 0.10.1
When I have all my selections made, and I press "i" or 
"a," only the deletion works! I mean it delete letter(s) from every 
selection and that is expected, but if I want to add letters 
only the last selection receive the letter and not the others 
selections.

Can you fix that?

Rgds,

PS: anyway is is an amazing work, when it works...

**Comment by brenton-leighton** [comment]
It sounds like it's a problem with the autocmd that handles character insertion. It could be due to compatibility with another plugin. Can you try adding `vim.print(char)` after line 13 in `lua/multiple-cursors/insert_mode/character.lua`? It should print a message with the character you've inserted.

**Comment by MrMic** [comment]
Hi,

Added as requested but nothing is printed anywhere...
Where should I look to see the character?

I am with AstroNvim so, may be, I have yo do things differently? no?

**Comment by MrMic** [comment]
Sorry i messed up with another plugin which is called "multicursors"

Sorry for the noise. My bad.
Rgds,
